In [1]:
import quandl
import pandas as pd
import requests
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import json
import datetime as dt

In [2]:
# Federal Debt: Total Public Debt as Percent of Gross Domestic Product, Quarterly
# Units: Percent of GDP, Seasonally Adjusted
# Source: FRED (Federal Reserve Bank St. Louis)

debt = quandl.get("FRED/GFDEGDQ188S", authtoken="ckJvd5G2a2dkK9nun3xS")

In [3]:
# S&P 500 Index Composite, Monthly
# Units: Index
# Source: Yale University, Online Data Robert Shiller

sp500 = quandl.get("YALE/SPCOMP", authtoken="ckJvd5G2a2dkK9nun3xS")

In [4]:
# Unemployment Rate, Quarterly
# Units: Percent, Seasonally Adjusted
# Source: FRED (Federal Reserve Bank St. Louis)

u = quandl.get("FRED/M0892AUSM156SNBR", authtoken="ckJvd5G2a2dkK9nun3xS")

In [5]:
# Trade Balance: Goods and Services, Balance of Payments Basis, Monthly
# Units: Millions of Dollars, Seasonally Adjusted 
# Source: FRED (Federal Reserve Bank St. Louis)

balance = quandl.get("FRED/BOPGSTB", authtoken="ckJvd5G2a2dkK9nun3xS")

In [8]:
sp = sp500.iloc[:,:1]

In [9]:
sp['Date'] = sp.index

/Users/flatironschool/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
sp['return'] =

            S&P Composite       Date
Year
1871-01-31           4.44 1871-01-31
1871-02-28           4.50 1871-02-28
1871-03-31           4.61 1871-03-31
1871-04-30           4.74 1871-04-30
1871-05-31           4.86 1871-05-31
1871-06-30           4.82 1871-06-30
1871-07-31           4.73 1871-07-31
1871-08-31           4.79 1871-08-31
1871-09-30           4.84 1871-09-30
1871-10-31           4.59 1871-10-31
1871-11-30           4.64 1871-11-30
1871-12-31           4.74 1871-12-31
1872-01-31           4.86 1872-01-31
1872-02-29           4.88 1872-02-29
1872-03-31           5.04 1872-03-31
1872-04-30           5.18 1872-04-30
1872-05-31           5.18 1872-05-31
1872-06-30           5.13 1872-06-30
1872-07-31           5.10 1872-07-31
1872-08-31           5.04 1872-08-31
1872-09-30           4.95 1872-09-30
1872-10-31           4.97 1872-10-31
1872-11-30           4.95 1872-11-30
1872-12-31           5.07 1872-12-31
1873-01-31           5.11 1873-01-31
1873-02-28           5.15 1873-02-28
1873-03-31           5.11 1873-03-31
1873-04-30           5.04 1873-04-30
1873-05-31           5.05 1873-05-31
1873-06-30           4.98 1873-06-30
...                   ...        ...
2017-03-31        2366.82 2017-03-31
2017-04-30        2359.31 2017-04-30
2017-05-31        2395.35 2017-05-31
2017-06-30        2433.99 2017-06-30
2017-07-31        2454.10 2017-07-31
2017-08-31        2456.22 2017-08-31
2017-09-30        2492.84 2017-09-30
2017-10-31        2557.00 2017-10-31
2017-11-30        2593.61 2017-11-30
2017-12-31        2664.34 2017-12-31
2018-01-31        2789.80 2018-01-31
2018-02-28        2705.16 2018-02-28
2018-03-31        2702.77 2018-03-31
2018-04-30        2653.63 2018-04-30
2018-05-31        2701.49 2018-05-31
2018-06-30        2754.35 2018-06-30
2018-07-31        2793.64 2018-07-31
2018-08-31        2857.82 2018-08-31
2018-09-30        2901.50 2018-09-30
2018-10-31        2785.46 2018-10-31
2018-11-30        2723.23 2018-11-30
2018-12-31        2567.31 2018-12-31
2019-01-31        2607.39 2019-01-31
2019-02-28        2754.86 2019-02-28
2019-03-31        2803.98 2019-03-31
2019-04-30        2903.80 2019-04-30
2019-05-31        2854.71 2019-05-31
2019-06-30        2890.17 2019-06-30
2019-07-31        2996.11 2019-07-31
2019-08-31        2883.98 2019-08-31

[1784 rows x 2 columns]